import {
  Home,
  Users,
  UserCheck,
  // Calendar,
  // CalendarDays,
  // FileText,
  // Receipt,
  // Activity,
  // FolderKanban,
  GraduationCap,
  UserCircle,
  BookOpen,
  MapPin,
  ClipboardList,
  MessageSquare,
  Award,
  Book,
  // FileBadge,
  // ChevronDown,
  // ChevronRight,
  // School,
  Building,
  // ClipboardCheck,
  FileBarChart,
  Shield,
  History,
} from "lucide-react";

export const MenuItems = [
  // Common / Shared
  {
    title: "Home",
    url: "/dashboard",
    icon: Home,
    allowedRoles: ["admin", "superadmin", "trainer", "candidate"],
  },
  {
    title: "Nominators",
    url: "/nominators",
    icon: Users,
    allowedRoles: ["admin", "superadmin"],
    permissionSlug: "view_nominators",
  },
  // Admin Specific
  {
    title: "Candidates",
    url: "/candidates",
    icon: UserCircle,
    allowedRoles: ["admin", "superadmin"],
    permissionSlug: "view_candidates",
    subItems: [
      { title: "MOLMI Candidates", url: "/candidates/molmi" },
      { title: "Other Candidates", url: "/candidates/others" },
    ],
  },
  {
    title: "Trainers",
    url: "/trainers",
    icon: GraduationCap,
    allowedRoles: ["admin", "superadmin"],
    permissionSlug: "view_trainers",
  },
  {
    title: "Courses",
    url: "/courses",
    icon: BookOpen,
    allowedRoles: ["admin", "superadmin"],
    permissionSlug: "view_master_courses",
    subItems: [
      { title: "Master Courses", url: "/courses" },
      // { title: "Pre-Active Courses", url: "/pre-active-courses" },
      // { title: "Active Courses", url: "/active-courses" },
    ],
  },

  {
    title: "Hotel Details",
    url: "/hotel-details",
    icon: Building,
    allowedRoles: ["admin", "superadmin"],
    code: "hotel_details",
    permissionSlug: "view_hotels",
  },
  // {
  //   title: "System Manual",
  //   icon: FileText,
  //   url: "/system-manual",
  //   allowedRoles: ["admin", "superadmin"], // Assuming it's for admin/superadmin based on placement
  //   code: "system_manual",
  // },
  {
    title: "Location",
    url: "/location",
    icon: MapPin,
    allowedRoles: ["admin", "superadmin"],
    permissionSlug: "view_locations",
  },
  {
    title: "Assessment",
    url: "/assessment",
    icon: ClipboardList,
    allowedRoles: ["admin", "superadmin"],
    subItems: [
      { title: "Question Bank", url: "/assessment/question-bank" },
      { title: "Assessments", url: "/assessment/assessments" },
      // { title: "Submitted Assessments", url: "/assessment/submitted" },
    ],
  },

  // {
  //   title: "Feedback",
  //   url: "/feedback",
  //   icon: MessageSquare,
  //   allowedRoles: ["admin", "superadmin"],
  //   subItems: [
  //     { title: "Feedback Category", url: "/feedback" },
  //     { title: "Feedback Question", url: "/feedback/forms" },
  //     { title: "Submitted Feedback", url: "/feedback/submitted" },
  //   ],
  // },
  // {
  //   title: "Certificates",
  //   url: "/certificates",
  //   icon: Award,
  //   allowedRoles: ["admin", "superadmin"],
  // },
  // {
  //   title: "Reports",
  //   url: "/reports",
  //   icon: FileBarChart,
  //   allowedRoles: ["admin", "superadmin"],
  //   subItems: [
  //     { title: "Reports", url: "/reports" },
  //     { title: "Hotel Report", url: "/reports/hotel" },
  //     { title: "Admin Remarks", url: "/reports/admin-remarks" },
  //   ],
  // },
  {
    title: "Role Permissions",
    url: "/admin/role-permissions",
    icon: Shield,
    allowedRoles: ["admin", "superadmin"],
    permissionSlug: "manage_permissions",
  },
  {
    title: "Log History",
    url: "/admin/log-history",
    icon: History,
    allowedRoles: ["admin", "superadmin"],
    permissionSlug: "view_logs",
  },
  {
    title: "Admin Roles",
    url: "/admin/admin-roles",
    icon: Shield,
    allowedRoles: ["admin", "superadmin"],
    permissionSlug: "manage_admin_roles",
  },
  {
    title: "Admin Users",
    url: "/admin/users",
    icon: UserCheck,
    allowedRoles: ["admin", "superadmin"],
    permissionSlug: "manage_admin_users",
  },

  // Trainer Specific
  {
    title: "My Courses",
    url: "/my-courses",
    icon: Book,
    allowedRoles: ["trainer"],
    requiredPermission: "view_courses",
  },
  {
    title: "Assessments",
    url: "/trainer-assessments",
    icon: Users,
    allowedRoles: ["trainer"],
    requiredPermission: "view_assessments",
  },
  {
    title: "Feedback",
    url: "/trainer-feedback",
    icon: MessageSquare,
    allowedRoles: ["trainer"],
    requiredPermission: "view_feedback",
  },
  {
    title: "Certificates",
    url: "/trainer-certificates",
    icon: Award,
    allowedRoles: ["trainer"],
    requiredPermission: "view_certificates",
  },

  // Candidate Specific
  {
    title: "My Courses",
    url: "/candidate-courses",
    icon: Book,
    allowedRoles: ["candidate"],
    requiredPermission: "view_courses",
  },
  {
    title: "My Certificates",
    url: "/candidate-certificates",
    icon: Award,
    allowedRoles: ["candidate"],
    requiredPermission: "view_certificates",
  },
];
